<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editingModel"
    nsURI="http://www.eclipse.org/emf/eef/editingmodel/1.0.0" nsPrefix="eef-model">
  <eClassifiers xsi:type="ecore:EClass" name="PropertiesEditingModel">
    <eOperations name="binding" eType="#//EClassBinding">
      <eParameters name="eObject" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="views" upperBound="-1" eType="#//View">
      <eParameters name="eObject" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//EClassBinding" containment="true" eOpposite="#//EClassBinding/editingModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedModels" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="#//EditingOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClassBinding">
    <eOperations name="propertyEditor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="eObject" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="feature" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
      <eParameters name="autowire" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="propertyBinding" eType="#//PropertyBinding">
      <eParameters name="view" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="autowire" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editingModel" lowerBound="1"
        eType="#//PropertiesEditingModel" eOpposite="#//PropertiesEditingModel/bindings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyBindings" upperBound="-1"
        eType="#//PropertyBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Editor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyBinding">
    <eOperations name="getValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="getChoiceOfValue" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" lowerBound="1"
        eType="#//Editor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPropertyBindings" upperBound="-1"
        eType="#//PropertyBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" upperBound="-1"
        eType="#//EditorSettings" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getter" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueProvider" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonoValuedPropertyBinding" eSuperTypes="#//PropertyBinding">
    <eOperations name="setValue" lowerBound="1" eType="#//Void">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="unsetValue" lowerBound="1" eType="#//Void">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setter" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="#//Void"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unsetter" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="#//Void"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiValuedPropertyBinding" eSuperTypes="#//PropertyBinding">
    <eOperations name="addValue" lowerBound="1" eType="#//Void">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeValue" lowerBound="1" eType="#//Void">
      <eParameters name="loader" lowerBound="1" eType="ecore:EDataType query.ecore#//ClassLoader"/>
      <eParameters name="target" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adder" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="#//Void"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="remover" containment="true">
      <eGenericType eClassifier="ecore:EClass query.ecore#//JavaBody">
        <eTypeArguments eClassifier="#//Void"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureBinding" eSuperTypes="#//MonoValuedPropertyBinding #//MultiValuedPropertyBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaEditor" eSuperTypes="#//Editor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectEditor" eSuperTypes="#//Editor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditingOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureDocumentationProvider"
        eType="#//FeatureDocumentationProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureDocumentationProvider">
    <eLiterals name="GenmodelPropertyDescription"/>
    <eLiterals name="EcoreDocumentation" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorSettings" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EReferenceFilter" eSuperTypes="#//EditorSettings query.ecore#//Filter"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Void" instanceClassName="java.lang.Void"/>
</ecore:EPackage>
