<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="query"
    nsURI="http://www.eclipse.org/emf/eef/query/1.0" nsPrefix="eef-query">
  <eClassifiers xsi:type="ecore:EClass" name="Query" abstract="true">
    <eTypeParameters name="TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" containment="true">
      <eGenericType eClassifier="#//Body">
        <eTypeArguments eTypeParameter="#//Query/TYPE"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Body" abstract="true">
    <eTypeParameters name="TYPE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaBody">
    <eTypeParameters name="TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//Body">
      <eTypeArguments eTypeParameter="#//JavaBody/TYPE"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" abstract="true">
    <eGenericSuperTypes eClassifier="#//Query">
      <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation">
    <eGenericSuperTypes eClassifier="#//Query">
      <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
